node {
  try {
    def commit_id
    stage('Preparation') {
      checkout scm
      sh 'git rev-parse --short HEAD > .git/commit-id'
      commit_id = readFile('.git/commit-id').trim()
    }
    stage('Install Dependencies') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'cd client && npm install'
      }
    }
    stage('Test') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'cd client && npm run test:ci'
      }
    }
    stage('Build') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'cd client && npm run build'
      }
    }
  } catch(e) {
    currentBuild.result = "FAILURE";
    throw e;
  }
}
